version: '3'

services:
  # my node blog-app
  blog-app:
    image: 133789211558.dkr.ecr.us-east-1.amazonaws.com/blog-app:1.0
    ports:
      - 3000:3000

  # 1st container - mongo database
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amrit
      - MONGO_INITDB_ROOT_PASSWORD=amrit
    ports:
      - 27017:27017
      
  # 2nd container - mongo-express UI
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=amrit
      - ME_CONFIG_MONGODB_ADMINPASSWORD=amrit
      - ME_CONFIG_MONGODB_SERVER=mongodb